#!/bin/bash
# Written by Nikhilesh Gupta, December 2023


# Define color codes
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# HELP | Checks if the Input is NULL
if [[ $1 = '-h' ]] || [[ -z $1 ]]
then
	echo "[+]Syntax for tool domv{DOMAIN-VALIDATION} is defined below";
	echo "	->domv <file.txt>";
	printf "${BLUE}[#]Note: The file should have the list of domains seperated with next line${NC}\n";
       printf "${BLUE}[#]Description: The tool will find the information about the domains from the WHOIS Database${NC}\n";

	exit 3;
fi;

for domains in `cat $1`; do
         echo "$domains";
         echo "--------------------";
         readarray -t out <<< "$(whois $domains | grep -i -e "Organisation" -e "OrgName" -e "OrgId" -e "OrgTechEmail" -e "org-name" -e "Registrant Name" -e "Registrant Organization" -e "Registrant Email" -e "Admin Name" -e "Admin Organization" -e "Admin Email")";
         if [[ ${out[@]} ]]; then
                printf -- "%s\n" "${out[@]}"
         else
                echo "No WHOIS record found. Please do a manual check on this IP";
         fi;
         echo -e "\n";
done
