#!/bin/bash
# Written by Nikhilesh Gupta, December 2023 [ Last Updated At : June 2024 ]

# Define color codes
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Function contains HELP information related to the script
help_and_syntax_section() {
		printf "${YELLOW}[+]Syntax for tool IP2PTR{IP-Address to PTR Record}:${NC}\n";
        printf "   -> ${CYAN}ip2ptr <file.txt>${NC}\n";
        printf "   -> ${CYAN}ip2ptr -i <IP-address>${NC}\n";
        printf "${YELLOW}[#]Description:${NC} ${BLUE}The tool will find the PTR records and gives output in CSV format which needs to be saved either using redirection '>' or 'tee' command${NC}\n";
		printf "${YELLOW}[#]Note:${NC} ${BLUE}The file should have the list of IPs seperated with next line${NC}\n";

        exit 0;
}

for_single_ip() {
	dig=$(dig -x $ip | grep -o "PTR.*" | tail -n 1);
	check=$(echo $dig | awk -s '{ printf $NF }')
	if [[ "PTR" == $check ]]
	then
        	echo "$ip,no ptr record found";
	else
        	echo "$ip,$check";
	fi;

	exit 0;
}

for_files_of_ips() {
	#For Files - default behaviour
	for ip in `cat $file`; do
		dig=$(dig -x $ip | grep -o "PTR.*" | tail -n 1);

		check=$(echo $dig | awk -s '{ printf $NF }')
	if [[ "PTR" == $check ]]
	then
		echo "$ip,no ptr record found";
	else
		echo "$ip,$check";
	fi;
	done;
}

# Function tp check of the file exists
check_file() {
        if ! [ -f $file ]
        then
                printf "${RED}[-]Error: The file $file doesn't exists. Please check the path or name of the file${NC}\n";
                exit 1;
        fi;
}

# Assigning variable(s) for user input
file="" # takes file which contains the data
ip="" # takes the value of an IP Address


# Checking if no command-line arguments is provided
if [[ -z $1 ]]; then
    cli_arg=false
else
    cli_arg=true
fi

if $cli_arg
then
	# To check if -h flag is provided
	if [[ $1 = '-h' ]]
	then
		help_and_syntax_section
	elif [[ $1 = '-i' ]]
	then
		ip=$2
		for_single_ip
	else
		file=$1
		check_file
		for_files_of_ips
	fi;
else
	# If no argument is provided
	help_and_syntax_section
fi;