#!/bin/bash
# Written by Nikhilesh Gupta, December 2023

# Define color codes
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# HELP | Checks if the Input is NULL
if [[ $1 = '-h' ]] || [[ -z $1 ]]
then
        echo "[+]Use the syntax defined below";
        echo "   -> ntmlrecon -f file.txt";
        printf "${BLUE}[#]Note: The file should have the list of domains/subdomains seperated with next line${NC}\n";
        printf "${BLUE}[#]Description: The tool will check of NTLM is observed on the HEADER${NC}\n";


	exit 3;
fi;

#Code for the list of domains!!
if [ $1 = '-f' ]
then
        if [ ! -f $2 ]
        then
                echo "[!]File doesn't exists. Please check the path again"

                exit 20;
        fi;
        #allDomains=`cat $2`;

        echo "[+]Input file - $2";
        #echo "[+]Target Domains - $allDomains";
        date;

        for domain in `cat $2`;do
                out=$(curl -I -sk -L https://$domain/ -m 5 | grep -i NTLM);
                if [[ ! -z $out ]]
                then
                        #echo $out;
                        echo "$domain  |  $out";
                fi;
        done;

#Checks if the inputed value is incorrect!!
else
        echo "[!]Please give valid input";
        echo "";
        echo "[+]Use the syntax defined below";
        echo "   -> ntlmrecon -f file.txt";

        exit 3;
fi;
